apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: frontend-pipelinerun
spec:
  pipelineRef:
    name: frontend-pipeline
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
	        claimName: task-pv-claim-front  # 작업공간을 영속적으로 설정

  params:   # 파이프라인에 전달할 파라미터 정의
    - name: git-url
      value: https://github.com/KimChungEon/tekton-cicd-front.git
    - name: git-revision
      value: main
    - name: docker-image
      value: 192.168.1.169:443/project/frontend:10.13
    - name: registry-url
      value: 192.168.1.169:443
    - name: registry-username
      value: admin
    - name: registry-password
      value: Harbor12345