apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-triggertemplate
spec:
  params:
    - name: git-url
    - name: git-revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: frontend-pipelinerun
      spec:
        pipelineRef:
          name: frontend-pipeline
        params:
          - name: git-url
            value: $(tt.params.git-url)   #  TriggerBinding으로부터 받은 git-url 파라미터
          - name: git-revision
            value: $(tt.params.git-revision)   # TriggerBinding으로부터 받은 git-revision 파라미터
          - name: docker-image
            value: 192.168.1.169:443/project/frontend:10.13
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: task-pv-claim-front